### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by simon-p-r** [ocedo/jsonschema-c#5]
Hi

I found this repo as one of the top searches for keywords json schema c, I managed to compile it on Windows and I am getting an error.  Just wondering whether this project is being used or if it is totally dead.

Thanks

**Comment by commodo** [comment]
hey 
it's pretty much dead
other priorities and such

the intent was to create a lib [on top of [libjson-c](http://github.com/json-c/json-c)] that handles JSON schema
I think we'll try to push that directly into json-c
It makes sense to have it there ; so far I've pushed JSON Pointer [RFC 6901], working to get JSON Patch integrated [RFC 6902], and hopefully get also JSON schema

**Comment by simon-p-r** [comment]
Thanks @commodo ideally you want the json schema validation to have its own api independant of backend.  I will see what changes you have made to see if I can learn anything.  I am currently using jansson for my json handling.

**Comment by commodo** [comment]
well, i didn't write this code;
this module was an internal project we started to handle JSON schema
